/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_benjaminguzman_Main */

#ifndef _Included_net_benjaminguzman_Main
#define _Included_net_benjaminguzman_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_benjaminguzman_Main
 * Method:    a
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_benjaminguzman_Main_a
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
